const projects = [
  {
    title: "Coders Corner",
    description:
      "Asimple application for improving coding(software development) Skills(for students and mentors).",
    techStackTitle: "Tech Stack",
    techStack: "JavaScript | HTML5 | CSS3 | jQuery | MDN API | Anime.js | AJAX",
    projectUrl: "https://putincake.github.io/Coders-Corner/",
    githubUrl: "https://github.com/mojib2014/Coders-Corner",
    image: "../images/portfolio/coderscorner.gif",
    category: "javascript",
  },
  {
    title: "Dent Soft",
    description:
      "Dent Soft (DS) is a streamlined and standardized electronic system specially designed for multiple users in dental clinics",
    techStackTitle: "Tech Stack",
    techStack:
      "React.js | MongoDB | Node.js | Dropzone/Cloudinary | Google Authentication | Reactstrap",
    projectUrl: "https://dent-soft.herokuapp.com/",
    githubUrl: "https://github.com/mojib2014/dent-soft",
    image: "../images/portfolio/dent-soft.gif",
    category: "MERN",
  },
  {
    title: "Vidly Movie App",
    description:
      "A simple movie app that allows you to sort by genre by title etc, like/dislike, pagination, and user authentication.",
    techStackTitle: "Tech Stack",
    techStack: "React.js | MongoDB | Node.js | Heruko, Git",
    projectUrl: "https://enigmatic-forest-05440.herokuapp.com/movies",
    githubUrl: "#",
    image: "../images/portfolio/vidly.png",
    category: "MERN",
  },
  {
    title: "Star Wars RPG",
    description:
      "A simple multiplayer swords game built with JavaScript, Bootstrap, jQuery.",
    techStackTitle: "Tech Stack",
    techStack: "JavaScript | jQuery | Bootstrap",
    projectUrl: "https://mojib2014.github.io/Unit-4-Game/",
    githubUrl: "https://github.com/mojib2014/Unit-4-Game",
    image: "../images/portfolio/starwar.png",
    category: "javascript",
  },
  {
    title: "Comfy House",
    description: "A simple ecomerce shopping cart",
    techStackTitle: "Tech Stack",
    techStack: "JavaScript | jQuery | HTML5 | CSS3",
    projectUrl: "https://vanilla-js-shoping-cart.netlify.app/",
    githubUrl: "#",
    image: "../images/portfolio/comfyhouse.png",
    category: "javascript",
  },
  {
    title: "Issue Tracker",
    description:
      "A simple web app for tracking issues with persistant data using localstorage(browser).",
    techStackTitle: "Tech Stack",
    techStack: "React | Local Storage(browser)",
    projectUrl: "https://codesandbox.io/s/react-issue-tracker-b2b46",
    githubUrl: "https://codesandbox.io/s/react-issue-tracker-b2b46",
    image: "../images/portfolio/issueTracker.png",
    category: "react",
  },
  {
    title: "Counter App",
    description: "A simple web shopping cart like app build with react.",
    techStackTitle: "Tech Stack",
    techStack: "React | Bootstrap | Fontawesome",
    projectUrl: "https://codesandbox.io/s/counter-app-6g8j6?file=/package.json",
    githubUrl: "https://codesandbox.io/s/counter-app-6g8j6?file=/package.json",
    image: "../images/portfolio/counter.png",
    category: "react",
  },
  {
    title: "My Train Scheduler",
    description:
      "A simple web app that allows you to schedule and check the status of your train.",
    techStackTitle: "Tech Stack",
    techStack: "JavaScript | HTML5 | CSS3 | Git | Firebase",
    projectUrl: "https://mojib2014.github.io/Train-Scheduler/",
    githubUrl: "https://github.com/mojib2014/Train-Scheduler",
    image: "../images/portfolio/trainScheduler.png",
    category: "javascript",
  },
  {
    title: "Crystal Collector",
    description:
      "You will be given a random number at the start of the game. There are four crystals below. By clicking on a crystal you will add a specific amount of points to your total score.",
    techStackTitle: "Tech Stack",
    techStack: "JavaScript | jQuery | Bootstrap",
    projectUrl: "https://mojib2014.github.io/Crystal-Collector-Game/",
    githubUrl: "https://github.com/mojib2014/Crystal-Collector-Game",
    image: "../images/portfolio/crystalCollector.png",
    category: "javascript",
  },
  {
    title: "Rock Paper Scissors",
    description:
      "A simple online real time multiplayer game, and players can chat with each other.",
    techStackTitle: "Tech Stack",
    techStack: "HTML | CSS | Reset css | Javascript | Firebase | jQuery",
    projectUrl: "https://mojib2014.github.io/RPS-Multiplayer/",
    githubUrl: "https://github.com/mojib2014/RPS-Multiplayer",
    image: "../images/portfolio/rockpaper.png",
    category: "javascript",
  },
  {
    title: "Los Palmas",
    description:
      "A simple coffee shopt website to demonstrate CSS3 and system design skills.",
    techStackTitle: "Tech Stack",
    techStack: "HTML | CSS | JavaScript",
    projectUrl: "https://mojib2014.github.io/responsive-club-website/#",
    githubUrl: "https://github.com/mojib2014/responsive-club-website/settings",
    image: "../images/portfolio/los-palmas.png",
    category: "javascript",
  },
  {
    title: "",
    description: "",
    techStackTitle: "",
    techStack: "",
    projectUrl: "",
    githubUrl: "",
    image: "",
    category: "PERN",
  },
];
